apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slipsync-backend-pvc
  labels:
    app: slipsync-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
