apiVersion: v1
kind: Service
metadata:
  name: slipsync-frontend-svc
spec:
  selector:
    app: slipsync-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
